version: '3'
services:
  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - 5432:5432
    volumes:
    - postgres/var/lib/postgresql/data  
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: inter